### ISSUE TITLE
`eval` trips up the backtrace formatter

### ISSUE THREAD

**Issue by garrettdimon** [garrettdimon/minitest-heat#4]
This was the result of an `assert_difference` call using `WebhookEvent.size` instead of `WebhookEvent.all.size`

```
Error:
Stripe::WebhookReceiverTest#test_creates_a_webhook_event_record:
NoMethodError: undefined method `size' for WebhookEvent:Class
    (eval):1:in `block in <class:WebhookReceiverTest>'
    test/services/stripe/webhook_receiver_test.rb:36:in `block in <class:WebhookReceiverTest>'
```

And here's the Minitest Heat backtrace:

```
Sorry, but Minitest Heat couldn't display output for a failure. Disabling Minitest Heat can get you back on track until the problem can be fixed.
Please use the following exception details to submit an issue at https://github.com/garrettdimon/minitest-heat/issues
undefined method `strip' for nil:NilClass:
  /Users/garrettdimon/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/minitest-heat-0.0.10/lib/minitest/heat/output/backtrace.rb:111:in `source_code_line_token'
  /Users/garrettdimon/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/minitest-heat-0.0.10/lib/minitest/heat/output/backtrace.rb:61:in `backtrace_line_tokens'
  /Users/garrettdimon/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/minitest-heat-0.0.10/lib/minitest/heat/output/backtrace.rb:26:in `block in tokens'
  /Users/garrettdimon/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/minitest-heat-0.0.10/lib/minitest/heat/output/backtrace.rb:24:in `each'
  /Users/garrettdimon/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/minitest-heat-0.0.10/lib/minitest/heat/output/backtrace.rb:24:in `tokens'
  /Users/garrettdimon/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/minitest-heat-0.0.10/lib/minitest/heat/output/issue.rb:123:in `backtrace_tokens'
  /Users/garrettdimon/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/minitest-heat-0.0.10/lib/minitest/heat/output/issue.rb:32:in `error_tokens'
  /Users/garrettdimon/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/minitest-heat-0.0.10/lib/minitest/heat/output/issue.rb:16:in `tokens'
  /Users/garrettdimon/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/minitest-heat-0.0.10/lib/minitest/heat/output.rb:65:in `issue_details'
  /Users/garrettdimon/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/minitest-heat-0.0.10/lib/minitest/heat/output.rb:57:in `block (2 levels) in issues_list'
  /Users/garrettdimon/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/minitest-heat-0.0.10/lib/minitest/heat/output.rb:57:in `each'
  /Users/garrettdimon/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/minitest-heat-0.0.10/lib/minitest/heat/output.rb:57:in `block in issues_list'
  /Users/garrettdimon/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/minitest-heat-0.0.10/lib/minitest/heat/output.rb:54:in `each'
  /Users/garrettdimon/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/minitest-heat-0.0.10/lib/minitest/heat/output.rb:54:in `issues_list'
  /Users/garrettdimon/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/minitest-heat-0.0.10/lib/minitest/heat_reporter.rb:93:in `report'
  /Users/garrettdimon/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/minitest-5.14.4/lib/minitest.rb:866:in `each'
  /Users/garrettdimon/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/minitest-5.14.4/lib/minitest.rb:866:in `report'
  /Users/garrettdimon/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/minitest-5.14.4/lib/minitest.rb:146:in `run'
  /Users/garrettdimon/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/minitest-5.14.4/lib/minitest.rb:68:in `block in autorun'
```

**Comment by garrettdimon** [comment]
I believe this was fixed with some other backtrace formatter improvements/bug fixes.
